// vue-app/src/components/Header.vue
<template>
  <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
      <div class="container">
        <router-link class="navbar-brand" to="/">WebApp</router-link>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
          <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
              <router-link class="nav-link text-dark" to="/categories/CategoryList">Categories</router-link>
            </li>
            <li class="nav-item">
              <router-link class="nav-link text-dark" to="/priorities/PriorityList">Priorities</router-link>
            </li>
            <li class="nav-item">
              <router-link class="nav-link text-dark" to="/tasks/TaskList">Tasks</router-link>
            </li>
          </ul>

          <ul class="navbar-nav">
            <template v-if="!authStore.isAuthenticated">
              <li class="nav-item">
                <router-link class="nav-link text-dark" to="/login">Login</router-link>
              </li>
              <li class="nav-item">
                <router-link class="nav-link text-dark" to="/register">Register</router-link>
              </li>
            </template>
            <template v-else>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Hello, {{ authStore.userName }}!
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li>
                    <a class="dropdown-item" @click="doLogout">Logout</a>
                  </li>
                </ul>
              </li>
            </template>
          </ul>
        </div>
      </div>
    </nav>
  </header>
</template>

<script setup>
import { useAuthStore } from '@/stores/auth';
import { useRouter } from 'vue-router';

const authStore = useAuthStore();
const router = useRouter();

const doLogout = () => {
  authStore.logout();
  router.push('/login');
}
</script>

// next-app/src/components/nav/Header.tsx
"use client"

import Link from "next/link";
import Identity from "./Identity";

export default function Header() {
    return (
        <header>
            <nav className="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div className="container">
                    <Link href="/" className="navbar-brand">WebApp</Link>
                    <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span className="navbar-toggler-icon"></span>
                    </button>
                    <div className="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul className="navbar-nav flex-grow-1">
                            <li className="nav-item">
                                <Link href="/todo/tasks" className="nav-link text-dark">Tasks</Link>
                            </li>
                            <li className="nav-item">
                                <Link href="/todo/categories" className="nav-link text-dark">Categories</Link>
                            </li>
                            <li className="nav-item">
                                <Link href="/todo/priorities" className="nav-link text-dark">Priorities</Link>
                            </li>

                        </ul>
                        <Identity />
                    </div>
                </div>
            </nav>
        </header>
    );
}
